// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddServer(arg1, arg2) {
  return window['go']['controllers']['SSHController']['AddServer'](arg1, arg2);
}

export function AddServerGroup(arg1) {
  return window['go']['controllers']['SSHController']['AddServerGroup'](arg1);
}

export function ClearTerminalOutputBuffer(arg1) {
  return window['go']['controllers']['SSHController']['ClearTerminalOutputBuffer'](arg1);
}

export function CloseTerminalSession(arg1) {
  return window['go']['controllers']['SSHController']['CloseTerminalSession'](arg1);
}

export function ConnectToServer(arg1) {
  return window['go']['controllers']['SSHController']['ConnectToServer'](arg1);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['controllers']['SSHController']['CreateDirectory'](arg1, arg2);
}

export function CreateSFTPClient(arg1) {
  return window['go']['controllers']['SSHController']['CreateSFTPClient'](arg1);
}

export function CreateTerminalSession(arg1) {
  return window['go']['controllers']['SSHController']['CreateTerminalSession'](arg1);
}

export function CreateTerminalSessionWithSize(arg1, arg2, arg3) {
  return window['go']['controllers']['SSHController']['CreateTerminalSessionWithSize'](arg1, arg2, arg3);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['controllers']['SSHController']['DeleteFile'](arg1, arg2);
}

export function DeleteServer(arg1, arg2) {
  return window['go']['controllers']['SSHController']['DeleteServer'](arg1, arg2);
}

export function DeleteServerGroup(arg1) {
  return window['go']['controllers']['SSHController']['DeleteServerGroup'](arg1);
}

export function DisconnectFromServer(arg1) {
  return window['go']['controllers']['SSHController']['DisconnectFromServer'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['controllers']['SSHController']['DownloadFile'](arg1, arg2, arg3);
}

export function ExecuteCommand(arg1, arg2) {
  return window['go']['controllers']['SSHController']['ExecuteCommand'](arg1, arg2);
}

export function ExecuteCommandWithoutNewline(arg1, arg2) {
  return window['go']['controllers']['SSHController']['ExecuteCommandWithoutNewline'](arg1, arg2);
}

export function GetAutoCompleteSuggestions(arg1, arg2) {
  return window['go']['controllers']['SSHController']['GetAutoCompleteSuggestions'](arg1, arg2);
}

export function GetServerGroups() {
  return window['go']['controllers']['SSHController']['GetServerGroups']();
}

export function GetTerminalLastOutput(arg1) {
  return window['go']['controllers']['SSHController']['GetTerminalLastOutput'](arg1);
}

export function IsTerminalSessionActive(arg1) {
  return window['go']['controllers']['SSHController']['IsTerminalSessionActive'](arg1);
}

export function ListDirectory(arg1, arg2) {
  return window['go']['controllers']['SSHController']['ListDirectory'](arg1, arg2);
}

export function ReadTerminalOutput(arg1) {
  return window['go']['controllers']['SSHController']['ReadTerminalOutput'](arg1);
}

export function ResizeTerminal(arg1, arg2, arg3) {
  return window['go']['controllers']['SSHController']['ResizeTerminal'](arg1, arg2, arg3);
}

export function SetEncryptionConfig(arg1, arg2) {
  return window['go']['controllers']['SSHController']['SetEncryptionConfig'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['controllers']['SSHController']['Startup'](arg1);
}

export function UpdateServer(arg1, arg2) {
  return window['go']['controllers']['SSHController']['UpdateServer'](arg1, arg2);
}

export function UpdateServerGroup(arg1) {
  return window['go']['controllers']['SSHController']['UpdateServerGroup'](arg1);
}

export function UploadFile(arg1, arg2, arg3) {
  return window['go']['controllers']['SSHController']['UploadFile'](arg1, arg2, arg3);
}
