// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';
import {context} from '../models';

export function AddServer(arg1:string,arg2:models.Server):Promise<void>;

export function AddServerGroup(arg1:models.ServerGroup):Promise<void>;

export function ClearTerminalOutputBuffer(arg1:string):Promise<void>;

export function CloseTerminalSession(arg1:string):Promise<string>;

export function ConnectToServer(arg1:string):Promise<string>;

export function CreateDirectory(arg1:string,arg2:string):Promise<string>;

export function CreateSFTPClient(arg1:string):Promise<string>;

export function CreateTerminalSession(arg1:string):Promise<string>;

export function CreateTerminalSessionWithSize(arg1:string,arg2:number,arg3:number):Promise<string>;

export function DeleteFile(arg1:string,arg2:string):Promise<string>;

export function DeleteServer(arg1:string,arg2:string):Promise<void>;

export function DeleteServerGroup(arg1:string):Promise<void>;

export function DisconnectFromServer(arg1:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExecuteCommand(arg1:string,arg2:string):Promise<string>;

export function ExecuteCommandWithoutNewline(arg1:string,arg2:string):Promise<string>;

export function GetAutoCompleteSuggestions(arg1:string,arg2:string):Promise<Array<string>>;

export function GetServerGroups():Promise<Array<models.ServerGroup>>;

export function GetTerminalLastOutput(arg1:string):Promise<string>;

export function IsTerminalSessionActive(arg1:string):Promise<boolean>;

export function ListDirectory(arg1:string,arg2:string):Promise<Array<services.FileInfo>>;

export function ReadTerminalOutput(arg1:string):Promise<string>;

export function ResizeTerminal(arg1:string,arg2:number,arg3:number):Promise<string>;

export function SetEncryptionConfig(arg1:boolean,arg2:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function UpdateServer(arg1:string,arg2:models.Server):Promise<void>;

export function UpdateServerGroup(arg1:models.ServerGroup):Promise<void>;

export function UploadFile(arg1:string,arg2:string,arg3:string):Promise<string>;
