// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * OpenFileDialog 打开文件选择对话框
 * @param {string} title
 * @param {application$0.FileFilter[]} filters
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog(title, filters) {
    return $Call.ByID(4196526771, title, filters);
}

/**
 * SaveFileDialog 打开文件保存对话框
 * @param {string} title
 * @param {string} defaultFilename
 * @returns {$CancellablePromise<string>}
 */
export function SaveFileDialog(title, defaultFilename) {
    return $Call.ByID(1166008166, title, defaultFilename);
}
