// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SSHController SSH控制器
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as services$0 from "../services/models.js";

/**
 * AddBatchScript 添加批量脚本
 * @param {models$0.BatchScript} script
 * @returns {$CancellablePromise<void>}
 */
export function AddBatchScript(script) {
    return $Call.ByID(3388401582, script);
}

/**
 * AddCommandHistory 追加命令历史
 * @param {string} serverID
 * @param {string} command
 * @returns {$CancellablePromise<void>}
 */
export function AddCommandHistory(serverID, command) {
    return $Call.ByID(3168375420, serverID, command);
}

/**
 * AddOpsConfig 新增运维配置
 * @param {models$0.OpsConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function AddOpsConfig(cfg) {
    return $Call.ByID(3916522155, cfg);
}

/**
 * AddPortForward 新增并启动端口转发
 * @param {string} serverID
 * @param {services$0.PortForward} fwd
 * @returns {$CancellablePromise<string>}
 */
export function AddPortForward(serverID, fwd) {
    return $Call.ByID(123291269, serverID, fwd);
}

/**
 * AddServer 添加服务器
 * @param {string} groupID
 * @param {models$0.Server} server
 * @returns {$CancellablePromise<void>}
 */
export function AddServer(groupID, server) {
    return $Call.ByID(3219258724, groupID, server);
}

/**
 * AddServerGroup 添加服务器分组
 * @param {models$0.ServerGroup} group
 * @returns {$CancellablePromise<void>}
 */
export function AddServerGroup(group) {
    return $Call.ByID(3250673623, group);
}

/**
 * AddSnippet 新增片段
 * @param {models$0.Snippet} s
 * @returns {$CancellablePromise<void>}
 */
export function AddSnippet(s) {
    return $Call.ByID(1097810180, s);
}

/**
 * ClearCommandHistory 清空命令历史
 * @param {string} serverID
 * @returns {$CancellablePromise<void>}
 */
export function ClearCommandHistory(serverID) {
    return $Call.ByID(6953934, serverID);
}

/**
 * ClearTerminalOutputBuffer 清空终端输出缓冲区
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function ClearTerminalOutputBuffer(sessionID) {
    return $Call.ByID(1344802790, sessionID);
}

/**
 * CloseTerminalSession 关闭指定的终端会话（按 sessionID 定向）
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function CloseTerminalSession(sessionID) {
    return $Call.ByID(1529066300, sessionID);
}

/**
 * ConnectByURI 解析 ssh://user[:pass]@host[:port] 或 user@host:port 一键直连（临时入库）
 * @param {string} uri
 * @returns {$CancellablePromise<string>}
 */
export function ConnectByURI(uri) {
    return $Call.ByID(2400119115, uri);
}

/**
 * ConnectToServer 连接到服务器（支持通过跳板机代理连接）
 * @param {string} serverID
 * @returns {$CancellablePromise<string>}
 */
export function ConnectToServer(serverID) {
    return $Call.ByID(3135199556, serverID);
}

/**
 * CreateDirectory 创建目录
 * @param {string} serverID
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function CreateDirectory(serverID, path) {
    return $Call.ByID(3751108259, serverID, path);
}

/**
 * CreateSFTPClient 创建SFTP客户端
 * @param {string} serverID
 * @returns {$CancellablePromise<string>}
 */
export function CreateSFTPClient(serverID) {
    return $Call.ByID(1106373834, serverID);
}

/**
 * CreateTerminalSessionWithSize 创建指定尺寸的终端会话，返回唯一 sessionID
 * 一个服务器可创建多个终端会话（支持"复制会话"）。
 * @param {string} serverID
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<string>}
 */
export function CreateTerminalSessionWithSize(serverID, width, height) {
    return $Call.ByID(2796285701, serverID, width, height);
}

/**
 * DeleteBatchScript 删除批量脚本
 * @param {string} scriptID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteBatchScript(scriptID) {
    return $Call.ByID(4174669726, scriptID);
}

/**
 * DeleteFile 删除文件或目录
 * @param {string} serverID
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function DeleteFile(serverID, path) {
    return $Call.ByID(1817789745, serverID, path);
}

/**
 * DeleteOpsConfig 删除运维配置
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteOpsConfig(id) {
    return $Call.ByID(1656685947, id);
}

/**
 * DeleteServer 删除服务器
 * @param {string} groupID
 * @param {string} serverID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteServer(groupID, serverID) {
    return $Call.ByID(1150843476, groupID, serverID);
}

/**
 * DeleteServerGroup 删除服务器分组
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteServerGroup(groupID) {
    return $Call.ByID(128477511, groupID);
}

/**
 * DeleteSnippet 删除片段
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSnippet(id) {
    return $Call.ByID(1063201812, id);
}

/**
 * DisconnectFromServer 断开服务器连接 - 修复死锁版本
 * @param {string} serverID
 * @returns {$CancellablePromise<string>}
 */
export function DisconnectFromServer(serverID) {
    return $Call.ByID(1157916189, serverID);
}

/**
 * DownloadFile 下载文件
 * @param {string} serverID
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<string>}
 */
export function DownloadFile(serverID, remotePath, localPath) {
    return $Call.ByID(2235050986, serverID, remotePath, localPath);
}

/**
 * DownloadFileWithProgress 带进度回调的下载文件（任务化：进度事件携带 taskID）
 * @param {string} serverID
 * @param {string} taskID
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<string>}
 */
export function DownloadFileWithProgress(serverID, taskID, remotePath, localPath) {
    return $Call.ByID(169134777, serverID, taskID, remotePath, localPath);
}

/**
 * EnableAutoReconnect 设置某服务器是否启用自动重连；关闭时取消正在进行的重连
 * @param {string} serverID
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function EnableAutoReconnect(serverID, enabled) {
    return $Call.ByID(1505408933, serverID, enabled);
}

/**
 * EnsureSFTPClient 确保SFTP客户端已创建
 * @param {string} serverID
 * @returns {$CancellablePromise<void>}
 */
export function EnsureSFTPClient(serverID) {
    return $Call.ByID(262157916, serverID);
}

/**
 * 实现CommandExecutor接口的方法（添加Exec前缀以避免命名冲突）
 * @param {string} serverID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function ExecCommand(serverID, command) {
    return $Call.ByID(3543342362, serverID, command);
}

/**
 * @param {string} serverID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function ExecCommandDirect(serverID, command) {
    return $Call.ByID(4224418123, serverID, command);
}

/**
 * @param {string} serverID
 * @param {string[]} commands
 * @returns {$CancellablePromise<string[]>}
 */
export function ExecCommandsInSharedSession(serverID, commands) {
    return $Call.ByID(3390164503, serverID, commands).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} serverID
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<string>}
 */
export function ExecDownloadFile(serverID, remotePath, localPath) {
    return $Call.ByID(487410135, serverID, remotePath, localPath);
}

/**
 * @param {string} serverID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function ExecUploadFile(serverID, localPath, remotePath) {
    return $Call.ByID(519652226, serverID, localPath, remotePath);
}

/**
 * ExecuteBatchScript 执行批量脚本（后端批量模式，结果通过返回值一次性返回）
 * @param {string} scriptID
 * @returns {$CancellablePromise<{ [_ in string]?: models$0.ScriptExecution }>}
 */
export function ExecuteBatchScript(scriptID) {
    return $Call.ByID(899286602, scriptID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ExecuteCommand 在服务器上执行命令（直接通过连接执行，不依赖终端会话，供批量脚本执行器使用）
 * @param {string} serverID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteCommand(serverID, command) {
    return $Call.ByID(10832416, serverID, command);
}

/**
 * ExecuteCommandWithoutNewline 执行命令但不添加换行符（按 sessionID 定向）
 * @param {string} sessionID
 * @param {string} command
 * @returns {$CancellablePromise<string>}
 */
export function ExecuteCommandWithoutNewline(sessionID, command) {
    return $Call.ByID(516402936, sessionID, command);
}

/**
 * GetAutoCompleteSuggestions 获取自动补全建议
 * @param {string} sessionID
 * @param {string} partialCommand
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAutoCompleteSuggestions(sessionID, partialCommand) {
    return $Call.ByID(608767129, sessionID, partialCommand).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetAutoReconnect 获取某服务器是否启用自动重连
 * @param {string} serverID
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoReconnect(serverID) {
    return $Call.ByID(3265724860, serverID);
}

/**
 * GetBatchScripts 获取所有批量脚本
 * @returns {$CancellablePromise<models$0.BatchScript[]>}
 */
export function GetBatchScripts() {
    return $Call.ByID(2440137272).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetCommandHistory 获取命令历史
 * @param {string} serverID
 * @returns {$CancellablePromise<string[]>}
 */
export function GetCommandHistory(serverID) {
    return $Call.ByID(1648454059, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetLastPath 获取服务器上次打开的目录
 * @param {string} serverID
 * @returns {$CancellablePromise<string>}
 */
export function GetLastPath(serverID) {
    return $Call.ByID(1566454087, serverID);
}

/**
 * GetOpsConfigs 获取所有运维配置
 * @returns {$CancellablePromise<models$0.OpsConfig[]>}
 */
export function GetOpsConfigs() {
    return $Call.ByID(2567766939).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetOpsConfigsByServer 获取指定服务器的运维配置
 * @param {string} serverID
 * @returns {$CancellablePromise<models$0.OpsConfig[]>}
 */
export function GetOpsConfigsByServer(serverID) {
    return $Call.ByID(2574129985, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetServerConnectionStatus 获取服务器连接状态
 * @returns {$CancellablePromise<{ [_ in string]?: boolean }>}
 */
export function GetServerConnectionStatus() {
    return $Call.ByID(499070653).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetServerGroups 获取所有服务器分组
 * @returns {$CancellablePromise<models$0.ServerGroup[]>}
 */
export function GetServerGroups() {
    return $Call.ByID(2482326835).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetSnippets 获取全部片段
 * @returns {$CancellablePromise<models$0.Snippet[]>}
 */
export function GetSnippets() {
    return $Call.ByID(591445970).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetTerminalLastOutput 获取终端最后的输出内容
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function GetTerminalLastOutput(sessionID) {
    return $Call.ByID(3010203733, sessionID);
}

/**
 * HandleFileDownloadRequest 处理文件下载请求（供终端内嵌下载使用）
 * @param {string} serverID
 * @param {string} remotePath
 * @param {string} localPath
 * @returns {$CancellablePromise<void>}
 */
export function HandleFileDownloadRequest(serverID, remotePath, localPath) {
    return $Call.ByID(3320240093, serverID, remotePath, localPath);
}

/**
 * HandleFileUploadRequest 处理文件上传请求（供终端内嵌上传使用）
 * @param {string} serverID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<void>}
 */
export function HandleFileUploadRequest(serverID, localPath, remotePath) {
    return $Call.ByID(1982326586, serverID, localPath, remotePath);
}

/**
 * InterruptCommand 中断当前正在执行的命令（发送 Ctrl+C，按 sessionID 定向）
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function InterruptCommand(sessionID) {
    return $Call.ByID(3487658740, sessionID);
}

/**
 * IsTerminalSessionActive 检查终端会话是否仍然活跃
 * @param {string} sessionID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsTerminalSessionActive(sessionID) {
    return $Call.ByID(1924397394, sessionID);
}

/**
 * ListDirectory 列出目录内容
 * @param {string} serverID
 * @param {string} path
 * @returns {$CancellablePromise<services$0.FileInfo[]>}
 */
export function ListDirectory(serverID, path) {
    return $Call.ByID(308139975, serverID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * ListPortForwards 列出端口转发
 * @param {string} serverID
 * @returns {$CancellablePromise<services$0.PortForward[]>}
 */
export function ListPortForwards(serverID) {
    return $Call.ByID(2715024629, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ReadTerminalOutput 读取终端输出
 * @param {string} sessionID
 * @returns {$CancellablePromise<string>}
 */
export function ReadTerminalOutput(sessionID) {
    return $Call.ByID(1298257821, sessionID);
}

/**
 * RemovePortForward 移除端口转发
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function RemovePortForward(id) {
    return $Call.ByID(4015633628, id);
}

/**
 * ResizeTerminal 调整终端大小（按 sessionID 定向）
 * @param {string} sessionID
 * @param {number} width
 * @param {number} height
 * @returns {$CancellablePromise<string>}
 */
export function ResizeTerminal(sessionID, width, height) {
    return $Call.ByID(2359397356, sessionID, width, height);
}

/**
 * SendScriptToTerminal 逐行发送脚本命令到指定终端会话（用于命令模式）
 * @param {string} scriptID
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function SendScriptToTerminal(scriptID, sessionID) {
    return $Call.ByID(1161228296, scriptID, sessionID);
}

/**
 * SetLastPath 记录服务器上次打开的目录并落盘
 * @param {string} serverID
 * @param {string} path
 * @returns {$CancellablePromise<string>}
 */
export function SetLastPath(serverID, path) {
    return $Call.ByID(955994251, serverID, path);
}

/**
 * UpdateBatchScript 更新批量脚本
 * @param {models$0.BatchScript} script
 * @returns {$CancellablePromise<void>}
 */
export function UpdateBatchScript(script) {
    return $Call.ByID(1137414140, script);
}

/**
 * UpdateOpsConfig 更新运维配置
 * @param {models$0.OpsConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateOpsConfig(cfg) {
    return $Call.ByID(835451961, cfg);
}

/**
 * UpdateServer 更新服务器
 * @param {string} groupID
 * @param {models$0.Server} server
 * @returns {$CancellablePromise<void>}
 */
export function UpdateServer(groupID, server) {
    return $Call.ByID(2751620354, groupID, server);
}

/**
 * UpdateServerGroup 更新服务器分组
 * @param {models$0.ServerGroup} group
 * @returns {$CancellablePromise<void>}
 */
export function UpdateServerGroup(group) {
    return $Call.ByID(3591887861, group);
}

/**
 * UpdateSnippet 更新片段
 * @param {models$0.Snippet} s
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSnippet(s) {
    return $Call.ByID(1275524206, s);
}

/**
 * UploadFile 上传文件
 * @param {string} serverID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function UploadFile(serverID, localPath, remotePath) {
    return $Call.ByID(1342918803, serverID, localPath, remotePath);
}

/**
 * UploadFileWithProgress 带进度回调的上传文件（任务化：进度事件携带 taskID）
 * @param {string} serverID
 * @param {string} taskID
 * @param {string} localPath
 * @param {string} remotePath
 * @returns {$CancellablePromise<string>}
 */
export function UploadFileWithProgress(serverID, taskID, localPath, remotePath) {
    return $Call.ByID(2878676740, serverID, taskID, localPath, remotePath);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = models$0.ScriptExecution.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = models$0.BatchScript.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = models$0.OpsConfig.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Map($Create.Any, $Create.Any);
const $$createType8 = models$0.ServerGroup.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = models$0.Snippet.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = services$0.FileInfo.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = services$0.PortForward.createFrom;
const $$createType15 = $Create.Array($$createType14);
