// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BatchScript 批量脚本
 */
export class BatchScript {
    /**
     * Creates a new BatchScript instance.
     * @param {Partial<BatchScript>} [$$source = {}] - The source object to create the BatchScript.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 脚本名称
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * 脚本描述
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * 脚本内容
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("serverIds" in $$source)) {
            /**
             * 目标服务器ID列表
             * @member
             * @type {string[]}
             */
            this["serverIds"] = [];
        }
        if (!("executionType" in $$source)) {
            /**
             * 执行类型: "script"(脚本模式), "command"(命令模式)
             * @member
             * @type {string}
             */
            this["executionType"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * 创建时间
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * 更新时间
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BatchScript instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BatchScript}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("serverIds" in $$parsedSource) {
            $$parsedSource["serverIds"] = $$createField4_0($$parsedSource["serverIds"]);
        }
        return new BatchScript(/** @type {Partial<BatchScript>} */($$parsedSource));
    }
}

/**
 * CommandOutput 单个命令的执行结果
 */
export class CommandOutput {
    /**
     * Creates a new CommandOutput instance.
     * @param {Partial<CommandOutput>} [$$source = {}] - The source object to create the CommandOutput.
     */
    constructor($$source = {}) {
        if (!("command" in $$source)) {
            /**
             * 命令内容
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * 命令输出
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * 命令错误
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 执行状态: success, failed
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * 开始时间
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            /**
             * 结束时间
             * @member
             * @type {string}
             */
            this["endTime"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommandOutput instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CommandOutput}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CommandOutput(/** @type {Partial<CommandOutput>} */($$parsedSource));
    }
}

/**
 * OpsConfig 运维配置：一个轻量的配置笔记，集中存放用户自填的运维信息。
 * 只保留最简字段：名称（用户自填）、关联项目（服务器）、以及一段自由文本（内容）。
 */
export class OpsConfig {
    /**
     * Creates a new OpsConfig instance.
     * @param {Partial<OpsConfig>} [$$source = {}] - The source object to create the OpsConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * 配置名称，由用户自填，例如 "生产-订单服务"
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("serverId" in $$source)) {
            /**
             * 关联的项目/服务器ID，可留空表示通用配置
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * 自由文本内容，由用户在全窗口文本框中输入
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * 更新时间
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OpsConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OpsConfig}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OpsConfig(/** @type {Partial<OpsConfig>} */($$parsedSource));
    }
}

/**
 * ScriptExecution 脚本执行记录
 */
export class ScriptExecution {
    /**
     * Creates a new ScriptExecution instance.
     * @param {Partial<ScriptExecution>} [$$source = {}] - The source object to create the ScriptExecution.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("scriptId" in $$source)) {
            /**
             * 脚本ID
             * @member
             * @type {string}
             */
            this["scriptId"] = "";
        }
        if (!("serverId" in $$source)) {
            /**
             * 服务器ID
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }
        if (!("serverName" in $$source)) {
            /**
             * 服务器名称
             * @member
             * @type {string}
             */
            this["serverName"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * 执行状态: pending, running, success, failed
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("output" in $$source)) {
            /**
             * 执行输出
             * @member
             * @type {string}
             */
            this["output"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * 错误信息
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("startTime" in $$source)) {
            /**
             * 开始时间
             * @member
             * @type {string}
             */
            this["startTime"] = "";
        }
        if (!("endTime" in $$source)) {
            /**
             * 结束时间
             * @member
             * @type {string}
             */
            this["endTime"] = "";
        }
        if (!("commandOutputs" in $$source)) {
            /**
             * 分命令的执行结果
             * @member
             * @type {CommandOutput[]}
             */
            this["commandOutputs"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScriptExecution instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScriptExecution}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("commandOutputs" in $$parsedSource) {
            $$parsedSource["commandOutputs"] = $$createField9_0($$parsedSource["commandOutputs"]);
        }
        return new ScriptExecution(/** @type {Partial<ScriptExecution>} */($$parsedSource));
    }
}

/**
 * Server 服务器信息
 */
export class Server {
    /**
     * Creates a new Server instance.
     * @param {Partial<Server>} [$$source = {}] - The source object to create the Server.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("username" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["username"] = "";
        }
        if (!("password" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["password"] = "";
        }
        if (!("keyFile" in $$source)) {
            /**
             * SSH密钥文件路径
             * @member
             * @type {string}
             */
            this["keyFile"] = "";
        }
        if (!("groupId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["groupId"] = "";
        }
        if (!("note" in $$source)) {
            /**
             * 备注信息
             * @member
             * @type {string}
             */
            this["note"] = "";
        }
        if (!("proxyJumpServerId" in $$source)) {
            /**
             * ProxyJumpServerID 跳板机：通过此已连接服务器代理连接本服务器（为空表示直连）
             * @member
             * @type {string}
             */
            this["proxyJumpServerId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Server instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Server}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Server(/** @type {Partial<Server>} */($$parsedSource));
    }
}

/**
 * ServerGroup 服务器分组
 */
export class ServerGroup {
    /**
     * Creates a new ServerGroup instance.
     * @param {Partial<ServerGroup>} [$$source = {}] - The source object to create the ServerGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("servers" in $$source)) {
            /**
             * @member
             * @type {Server[]}
             */
            this["servers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerGroup}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("servers" in $$parsedSource) {
            $$parsedSource["servers"] = $$createField2_0($$parsedSource["servers"]);
        }
        return new ServerGroup(/** @type {Partial<ServerGroup>} */($$parsedSource));
    }
}

/**
 * Snippet 命令片段：保存常用命令，可一键发送到终端。
 */
export class Snippet {
    /**
     * Creates a new Snippet instance.
     * @param {Partial<Snippet>} [$$source = {}] - The source object to create the Snippet.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("serverId" in $$source)) {
            /**
             * 可选：关联服务器（为空表示通用）
             * @member
             * @type {string}
             */
            this["serverId"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snippet}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snippet(/** @type {Partial<Snippet>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = CommandOutput.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = Server.createFrom;
const $$createType4 = $Create.Array($$createType3);
